"""empty message

Revision ID: 60edcc9bbcae
Revises: e2c86ad35888
Create Date: 2021-04-16 17:24:57.602361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60edcc9bbcae'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('epoca_siembra', sa.String(length=120), nullable=False),
    sa.Column('clima', sa.String(length=120), nullable=False),
    sa.Column('cosecha', sa.String(length=120), nullable=False),
    sa.Column('plagas', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('veg_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['veg_fav'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('firstName', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_table('fav')
    op.drop_table('post')
    # ### end Alembic commands ###
