"""empty message

Revision ID: 79389f4b95fe
Revises: 
Create Date: 2021-04-22 18:24:09.966040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79389f4b95fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('epoca_siembra', sa.String(), nullable=False),
    sa.Column('clima', sa.String(), nullable=False),
    sa.Column('cosecha', sa.String(), nullable=False),
    sa.Column('plagas', sa.String(), nullable=False),
    sa.Column('tipo_de_suelo', sa.String(), nullable=False),
    sa.Column('preparacion_del_suelo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('veg_fav', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['veg_fav'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
