"""empty message

Revision ID: c6779907fadf
Revises: 839d51993529
Create Date: 2021-04-20 17:19:20.580200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6779907fadf'
down_revision = '839d51993529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fav', 'name')
    # ### end Alembic commands ###
